static const char* INIT_COMMAND = 
"#\n"
"# This file is converted into a big C string during the build\n"
"# process and evaluated in the command interpreter at startup\n"
"# time.\n"
"#\n"
"\n"
"#\n"
"# For the vwait in event_loop to work, we need to make sure there's at\n"
"# least one event outstanding at all times, otherwise 'vwait forever'\n"
"# doesn't work\n"
"#\n"
"proc after_forever {} {\n"
"    after 1000000 after_forever\n"
"}\n"
"\n"
"#\n"
"# Run the event loop and no command line interpreter\n"
"#\n"
"proc event_loop {} {\n"
"    global forever\n"
"    after_forever\n"
"    vwait forever\n"
"}\n"
"\n"
"#\n"
"# Callback when there's data ready to be processed on stdin.\n"
"#\n"
"proc command_process {} {\n"
"    global command command_prompt\n"
"\n"
"    # Grab the line, append it to the batched up command, and check if\n"
"    # it's complete\n"
"    if {[gets stdin line] == -1} {\n"
"	exit 0\n"
"    }\n"
"\n"
"    append command $line\n"
"    if {![info complete $command]} {\n"
"	return\n"
"    }\n"
"\n"
"    # trim and evaluate the command\n"
"    set command [string trim $command]\n"
"    if {[catch {uplevel \\#0 $command} result]} {\n"
"	global errorInfo\n"
"	puts \"error: $result\\nwhile executing\\n$errorInfo\"\n"
"    } elseif {$result != \"\"} {\n"
"	puts $result\n"
"    }\n"
"    \n"
"    set command \"\"\n"
"    puts -nonewline $command_prompt\n"
"    flush stdout\n"
"}\n"
"    \n"
"# Run the command loop with the given prompt\n"
"proc command_loop {prompt} {\n"
"    global command_prompt forever\n"
"    set command_prompt \"${prompt}% \"\n"
"    \n"
"    if [catch {\n"
"	package require tclreadline\n"
"	namespace eval tclreadline {\n"
"	    proc prompt1 {} {\n"
"		global command_prompt\n"
"		return $command_prompt\n"
"	    }\n"
"	}\n"
"\n"
"	tclreadline::Loop\n"
"    } err] {\n"
"	log /tcl INFO \"can't load tclreadline: $err\"\n"
"	log /tcl INFO \"fall back to simple command loop\"\n"
"\n"
"	puts -nonewline $command_prompt\n"
"	flush stdout\n"
"	\n"
"	fileevent stdin readable command_process\n"
"\n"
"	after_forever\n"
"	vwait forever\n"
"    }\n"
"}\n"
"\n"
"# Define a bgerror proc to print the error stack when errors occur in\n"
"# event handlers\n"
"proc bgerror {err} {\n"
"    global errorInfo\n"
"    puts \"tcl error: $err\\n$errorInfo\"\n"
"}\n"
"\n"
;
